name: K6 full test
on: [push]
jobs:
  K6_full_test:
    runs-on: ubuntu-latest
    steps:
      - name: step 1 - checkout
        uses: actions/checkout@v3

      - name: step 2 - run K6 full test
        run: npm test
