name: K6 full test
on: [push]
jobs:
  K6_full_test:
    runs-on: ubuntu-latest
    steps:
      - name: step 1 - checkout
        uses: actions/checkout@v3

      - name: step 2 - Install K6
        run: npm install -g k6

      - name: step 3 - Run K6 full test
        run: npm test
